# Staging Environment Configuration
environment: staging
namespace: elice-devops-stg

# Resource Limits
resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# Scaling
replicaCount: 2
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

# Database Configuration
database:
  host: "elice-stg-cluster.cluster-xyz.us-west-2.rds.amazonaws.com"
  port: 5432
  ssl_mode: "require"
  max_connections: 10

# External Services
services:
  minio:
    enabled: true
    endpoint: "http://minio.elice-devops-stg.svc.cluster.local:9000"
  redis:
    enabled: true
    host: "redis.elice-devops-stg.svc.cluster.local"
    port: 6379

# Security
security:
  networkPolicies: true
  podSecurityPolicy: true
  serviceAccount: "elice-staging-sa"

# Monitoring
monitoring:
  enabled: true
  metrics:
    enabled: true
    path: "/metrics"
  logging:
    level: "INFO"
  traces:
    enabled: true
    samplingRate: 0.1

# Feature Flags
features:
  newUserOnboarding: true
  advancedAnalytics: true
  experimentalFeatures: true