apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: elice-devops-stg
  labels:
    app: inventory-service
    environment: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: 949019836804.dkr.ecr.ap-northeast-2.amazonaws.com/elice-devops-stg-inventory-service:stg-20250712-184105-0591c2a
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: SERVICE_NAME
          value: "inventory-service"
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: elice-devops-stg
  labels:
    app: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP 