apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: elice-devops-prod
type: Opaque
data:
  # minio / minio123 (base64 encoded)
  access-key: bWluaW8=
  secret-key: bWluaW8xMjM=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: elice-devops-prod
data:
  MINIO_ROOT_USER: minio
  MINIO_ROOT_PASSWORD: minio123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: elice-devops-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command:
        - /bin/bash
        - -c
        args:
        - minio server /data --console-address :9001
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            configMapKeyRef:
              name: minio-config
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: minio-config
              key: MINIO_ROOT_PASSWORD
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        volumeMounts:
        - name: storage
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: minio-storage
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: elice-devops-prod
spec:
  selector:
    app: minio
  ports:
  - name: api
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console-lb
  namespace: elice-devops-prod
spec:
  selector:
    app: minio
  ports:
  - name: console
    port: 9001
    targetPort: 9001
  type: LoadBalancer 