global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Elice 마이크로서비스들 모니터링
  - job_name: 'elice-api-gateway'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'elice-user-service'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'elice-auth-service'
    static_configs:
      - targets: ['host.docker.internal:8092']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'elice-product-service'
    static_configs:
      - targets: ['host.docker.internal:8083']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'elice-inventory-service'
    static_configs:
      - targets: ['host.docker.internal:8084']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'elice-order-service'
    static_configs:
      - targets: ['host.docker.internal:8085']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'elice-payment-service'
    static_configs:
      - targets: ['host.docker.internal:8086']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'elice-notification-service'
    static_configs:
      - targets: ['host.docker.internal:8087']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'elice-review-service'
    static_configs:
      - targets: ['host.docker.internal:8088']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'elice-analytics-service'
    static_configs:
      - targets: ['host.docker.internal:8089']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'elice-log-service'
    static_configs:
      - targets: ['host.docker.internal:8090']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'elice-health-service'
    static_configs:
      - targets: ['host.docker.internal:8091']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL 모니터링 (옵션)
  - job_name: 'elice-postgres'
    static_configs:
      - targets: ['host.docker.internal:5432']
    metrics_path: '/metrics'
    scrape_interval: 60s 