# 04-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
  namespace: jenkins
data:
  jenkins.yaml: |
    jenkins:
      systemMessage: "Elice DevOps CI/CD Pipeline - Production Ready"
      numExecutors: 4
      mode: NORMAL
      scmCheckoutRetryCount: 3

      securityRealm:
        local:
          allowsSignup: false
          users:
            - id: "admin"
              password: "${JENKINS_ADMIN_PASSWORD:-elice_admin}"
              
      authorizationStrategy:
        globalMatrix:
          permissions:
            - "Overall/Administer:admin"
            - "Overall/Read:authenticated"
            - "Job/Build:authenticated"
            - "Job/Cancel:authenticated"
            - "Job/Read:authenticated"

      remotingSecurity:
        enabled: true

      globalNodeProperties:
        - envVars:
            env:
              - key: "UV_CACHE_DIR"
                value: "/var/jenkins_cache/uv"
              - key: "DOCKER_REGISTRY"
                value: "localhost:5000"

    tool:
      git:
        installations:
          - name: "Default"
            home: "/usr/bin/git"

    # credentials 섹션 제거 - 환경변수 누락으로 인한 오류 방지
    # jobs 섹션 제거 - 복잡한 GitHub 플러그인 설정으로 인한 오류 방지

    unclassified:
      location:
        url: "http://localhost:8080/"

      # buildDiscarders, slackNotifier, prometheus 설정 제거 
      # - 관련 플러그인이 없거나 환경변수 누락으로 인한 오류 방지
