# 05-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/prometheus"
    spec:
      serviceAccountName: jenkins-sa
      # imagePullSecrets: 로컬 개발환경에서는 불필요
      # - name: registry-credentials
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        supplementalGroups: [117]  # Docker 그룹 추가
      initContainers:
        - name: fix-permissions
          image: busybox:1.35
          command: ["sh", "-c", "chown -R 1000:1000 /var/jenkins_home"]
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
          securityContext:
            runAsUser: 0
      containers:
        - name: jenkins
          image: donghyeonshin/elice-jenkins:v1.0.0  # 커스텀 Jenkins 이미지
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: jnlp
              containerPort: 50000
            - name: prometheus
              containerPort: 9090
          env:
            - name: JAVA_OPTS
              value: >-
                -Xmx2048m
                -Xms1024m
                -Djava.awt.headless=true
                -Djenkins.install.runSetupWizard=false
                -Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true
            - name: JENKINS_OPTS
              value: >-
                --httpPort=8080
                --httpsPort=-1
            - name: CASC_JENKINS_CONFIG
              value: /var/jenkins_config/jenkins.yaml
            - name: JENKINS_ADMIN_PASSWORD
              value: "elice_admin"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: jenkins-config
              mountPath: /var/jenkins_config
              readOnly: true
            - name: docker-sock
              mountPath: /var/run/docker.sock
              readOnly: true
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc
        - name: jenkins-config
          configMap:
            name: jenkins-config
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
