apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: elice-devops-prod
  labels:
    app: auth-service
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: 949019836804.dkr.ecr.ap-northeast-2.amazonaws.com/elice-devops-prod-auth-service:prod-20250712-184430-0591c2a
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: SERVICE_NAME
          value: "auth-service"
        - name: PORT
          value: "8080"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: auth-db-secret
              key: database-url
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: auth-db-secret
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-db-secret
              key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: elice-devops-prod
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
  namespace: elice-devops-prod
type: Opaque
data:
  # 실제 환경에서는 AWS Secrets Manager나 External Secrets Operator를 사용하세요
  database-url: cG9zdGdyZXNxbDovL2VsaWNlLWRldm9wcy1kZXYtYXV0aC1kYi5jaDJhMG84dGZwZDAuYXAtbm9ydGhlYXN0LTIucmRzLmFtYXpvbmF3cy5jb206NTQzMi9hdXRoX2Ri
  username: YXV0aF91c2Vy
  password: cGFzc3dvcmQxMjM= 