apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: elice-devops-prod
  labels:
    app: notification-service
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: 949019836804.dkr.ecr.ap-northeast-2.amazonaws.com/elice-devops-prod-notification-service:prod-20250712-184430-0591c2a
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: SERVICE_NAME
          value: "notification-service"
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: elice-devops-prod
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP 